apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-sidecar
  namespace: otel-sidecar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otel-sidecar
  template:
    metadata:
      labels:
        app: otel-sidecar
      annotations:
        sidecar.opentelemetry.io/inject: 'true'
    spec:
      containers:
        - name: otel-sidecar
          image: ko://github.com/houshengbo/kubecon-2025-eu/cmd/application
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otel-sidecar-service
  namespace: otel-sidecar
spec:
  selector:
    app: otel-sidecar
  ports:
    - name: usercontainer
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: sidecar
      protocol: TCP
      port: 1234
      targetPort: 1234
  sessionAffinity: None
  type: ClusterIP
