apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: otel-sidecar
  namespace: otel-sidecar
spec:
  scaleTargetRef:
    name: otel-sidecar
  triggers:
    - type: external
      metadata:
        scalerAddress: "keda-otel-scaler.keda.svc:4318"
        metricQuery: "sum(http_active_requests{namespace=otel-sidecar, deployment=otel-sidecar})"
        operationOverTime: "avg"
        targetValue: "20"
  minReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
        scaleUp:
          stabilizationWindowSeconds: 10
