apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kubecon-2025-eu
  namespace: otel-sidecar
spec:
  scaleTargetRef:
    name: kubecon-2025-eu
  triggers:
    - type: external
      metadata:
        scalerAddress: "keda-otel-scaler.keda.svc:4318"
        metricQuery: "avg(http_active_requests{deployment=kubecon-2025-eu, namespace=otel-sidecar})"
        operationOverTime: "avg"
        targetValue: "55"
        clampMax: "600"
  minReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
        scaleUp:
          stabilizationWindowSeconds: 10
