apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
  namespace: otel
spec:
  mode: sidecar
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
            - targets: ['0.0.0.0:8000']
    processors:
    exporters:
      debug:
      #prometheus:
        #endpoint: ${env:MY_POD_IP}:8889
      prometheus:
        endpoint: kubecon-2025-eu-service.otel.svc.cluster-domain.local:9090
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [debug, prometheus]
