apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-standalone-template
  namespace: otel-standalone
spec:
  mode: deployment
  config:
    receivers:
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
            - targets: ['kubecon-2025-eu-service.otel-standalone.svc:8000']
    processors:
      resourcedetection/env:
        detectors: [env]
        timeout: 2s
        override: false
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["host"], resource.attributes["net.host.name"])
    exporters:
      otlp/keda:
        endpoint: keda-otel-scaler.keda.svc:4317
        compression: "none"
        tls:
          insecure: true
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:1234"
        metric_expiration: 180m
        enable_open_metrics: true
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          #processors: [resourcedetection/env, transform]
          exporters: [debug, otlp/keda]
