apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-2025-eu
  namespace: otel-standalone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubecon-2025-eu
  template:
    metadata:
      labels:
        app: kubecon-2025-eu
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: kubecon-2025-eu
          image: ko://github.com/houshengbo/kubecon-2025-eu/cmd/application
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kubecon-2025-eu-service
  namespace: otel-standalone
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: kubecon-2025-eu
  ports:
    - name: usercontainer
      protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None
  type: LoadBalancer
