apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-standalone
  namespace: otel-standalone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otel-standalone
  template:
    metadata:
      labels:
        app: otel-standalone
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        #prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: otel-standalone
          image: ko://github.com/houshengbo/kubecon-2025-eu/cmd/application
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otel-standalone-service
  namespace: otel-standalone
  annotations:
    prometheus.io/scrape: "true"
    #prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: otel-standalone
  ports:
    - name: usercontainer
      protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None
  type: LoadBalancer
