apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kubecon-2025-eu
  namespace: otel-standalone
spec:
  scaleTargetRef:
    name: kubecon-2025-eu
  triggers:
    - type: external
      metadata:
        scalerAddress: "keda-otel-scaler.keda.svc:4318"
        metricQuery: "sum(http_active_requests)"
        #operationOverTime: "avg"
        targetValue: "1000"
        #clampMax: "600"
  minReplicaCount: 2
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
        scaleUp:
          stabilizationWindowSeconds: 10
